name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots -DskipTests package
      - name: Test
        run: ./mvnw --batch-mode test
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1